const SITE = {
  name: "TIBGSTORE",
  short: "TIBG",
  tagline: "Rigs for every budget.",
  blurb: "Prebuilt gaming PCs and individual parts. Assembled in-house, stress-tested for 24 hours, then shipped ready to play.",
  email: "hello@tibgstore.com",
  phone: "+1 (415) 555-1842",
  phoneHref: "tel:+14155551842",
  hours: "Mon–Sat, 10am–7pm PT",
  address: "1842 Folsom St, San Francisco, CA",
  instagram: "https://instagram.com/tibgstore",
  youtube: "https://youtube.com/@tibgstore",
  freeShipAt: 99999,
  shipFee: 999,
  codFee: 500,
};

const TIERS = {
  budget: {
    id: "budget",
    label: "Budget",
    kicker: "1080p · everyday",
    title: "Budget builds",
    href: "budget.html",
    priceFrom: 44999,
    blurb: "Honest 1080p machines for classwork, esports, and first-time builders who want something that just works.",
    image: "assets/images/pc-budget.jpg",
    color: "budget",
  },
  mid: {
    id: "mid",
    label: "Mid-range",
    kicker: "1440p · sweet spot",
    title: "Mid-range builds",
    href: "mid-range.html",
    priceFrom: 114699,
    blurb: "High-refresh 1440p gaming and creator work without stepping into flagship pricing.",
    image: "assets/images/pc-mid.jpg",
    color: "mid",
  },
  high: {
    id: "high",
    label: "High-end",
    kicker: "4K · no compromise",
    title: "High-end builds",
    href: "high-end.html",
    priceFrom: 237899,
    blurb: "4K ultra, ray tracing, and heavy renders. The machines we build when someone says do not hold back.",
    image: "assets/images/pc-high.jpg",
    color: "high",
  },
};

const PART_CATS = [
  { id: "cpu", label: "Processors", image: "assets/images/part-cpu.jpg" },
  { id: "gpu", label: "Graphics cards", image: "assets/images/part-gpu.jpg" },
  { id: "ram", label: "Memory", image: "assets/images/part-ram.jpg" },
  { id: "storage", label: "Storage", image: "assets/images/part-ssd.jpg" },
  { id: "motherboard", label: "Motherboards", image: "assets/images/part-mb.jpg" },
  { id: "psu", label: "Power supplies", image: "assets/images/part-psu.jpg" },
  { id: "cooler", label: "Cooling", image: "assets/images/part-cooler.jpg" },
  { id: "case", label: "Cases", image: "assets/images/part-case.jpg" },
];

let POSTS = [
  {
    id: "how-we-spec-a-budget-pc",
    title: "How we spec a budget PC that will not embarrass you",
    excerpt: "The 1080p floor we will actually put our name on — and the corners we refuse to cut.",
    cover: "assets/images/pc-budget.jpg",
    date: "2026-08-12",
    published: true,
    body: "A budget PC is not a junk drawer. It is a machine with one job: play and work at 1080p without sounding like a leaf blower or dying in thirteen months.",
  },
  {
    id: "call-us-before-you-buy-a-5090",
    title: "Call us before you buy a 5090",
    excerpt: "The card is fine. The rest of the list usually is not.",
    cover: "assets/images/part-gpu.jpg",
    date: "2026-08-20",
    published: true,
    body: "We will sell you a 5090. We will not sell you a 5090 into a 750W unit.",
  },
  {
    id: "what-24-hour-burn-in-actually-means",
    title: "What 24-hour burn-in actually means",
    excerpt: "Not a sticker. A log. CPU and GPU load, a game pass, and a photo of your unit.",
    cover: "assets/images/workshop.jpg",
    date: "2026-08-04",
    published: true,
    body: "Every complete PC and every Custom Build with assembly sits on the bench overnight.",
  },
];
let APP_CONFIG = { stripeEnabled: false, publishableKey: "", googleEnabled: false, user: null, ready: false, accountPath: "", wishlist: [] };

const IN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat",
  "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh",
  "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh",
  "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh",
  "Lakshadweep", "Puducherry",
];

const ORDER_LABELS = {
  pending: "Awaiting payment",
  paid: "Paid",
  cod: "COD",
  packed: "Packed",
  shipped: "Shipped",
  delivered: "Delivered",
  cancelled: "Cancelled",
};

function statusBox(status) {
  const key = String(status || "pending").toLowerCase();
  const label = ORDER_LABELS[key] || status || "Pending";
  return `<span class="st-box st-${key}">${label}</span>`;
}

let PRODUCTS = [
  /* ───────── Budget builds ───────── */
  {
    id: "office-plus",
    type: "build",
    tier: "budget",
    name: "TIBG Office+",
    tagline: "Quiet daily driver",
    price: 44999,
    image: "assets/images/pc-budget.jpg",
    images: ["assets/images/pc-budget.jpg", "assets/images/part-cpu.jpg", "assets/images/part-case.jpg"],
    badge: "Everyday",
    resolution: "1080p",
    stock: 14,
    rating: 4.7,
    reviews: 86,
    specs: {
      CPU: "AMD Ryzen 5 8600G",
      GPU: "Radeon 760M (integrated)",
      RAM: "16GB DDR5-6000",
      Storage: "1TB Gen4 NVMe",
      Motherboard: "B650 Micro-ATX",
      PSU: "550W 80+ Bronze",
      Cooler: "Stock AMD Wraith",
      Case: "Compact mesh mATX",
    },
    fps: [
      { game: "Valorant", fps: "240+" },
      { game: "League of Legends", fps: "200+" },
      { game: "Fortnite (perf)", fps: "120" },
    ],
    highlights: ["Silent enough for a desk", "Handles Office, Zoom, light Steam", "Upgradeable GPU later"],
    description:
      "A clean APU build for school, office work, and light esports. No discrete GPU today — room on the riser if you add one later.",
  },
  {
    id: "core-lite",
    type: "build",
    tier: "budget",
    name: "TIBG Core Lite",
    tagline: "First real gaming PC",
    price: 59399,
    image: "assets/images/pc-budget-2.jpg",
    images: ["assets/images/pc-budget-2.jpg", "assets/images/part-gpu.jpg", "assets/images/pc-budget.jpg"],
    badge: "Starter",
    resolution: "1080p",
    stock: 9,
    rating: 4.6,
    reviews: 54,
    specs: {
      CPU: "Intel Core Ultra 5 225F",
      GPU: "GeForce RTX 5050 8GB",
      RAM: "16GB DDR5-6000",
      Storage: "1TB Gen4 NVMe",
      Motherboard: "B860",
      PSU: "650W 80+ Bronze",
      Cooler: "Dual-tower air",
      Case: "Mesh mid-tower",
    },
    fps: [
      { game: "Cyberpunk 2077", fps: "70" },
      { game: "Fortnite", fps: "144" },
      { game: "Apex Legends", fps: "130" },
    ],
    highlights: ["Dedicated RTX 50-series GPU", "DLSS 4 on newer titles", "Windows 11 Pro included"],
    description:
      "The first machine we recommend when someone says they actually want to game. Solid 1080p ultra, respectable 1440p with DLSS.",
  },
  {
    id: "spark",
    type: "build",
    tier: "budget",
    name: "TIBG Spark",
    tagline: "AMD value 1080p",
    price: 63699,
    compareAt: 67899,
    image: "assets/images/pc-budget.jpg",
    images: ["assets/images/pc-budget.jpg", "assets/images/part-gpu.jpg", "assets/images/part-ram.jpg"],
    badge: "Sale",
    resolution: "1080p",
    stock: 7,
    rating: 4.8,
    reviews: 41,
    specs: {
      CPU: "AMD Ryzen 5 7600",
      GPU: "Radeon RX 9060 8GB",
      RAM: "16GB DDR5-6000",
      Storage: "1TB Gen4 NVMe",
      Motherboard: "B650",
      PSU: "650W 80+ Gold",
      Cooler: "Dual-tower air",
      Case: "Mesh mid-tower",
    },
    fps: [
      { game: "Warzone", fps: "110" },
      { game: "Elden Ring", fps: "90" },
      { game: "CS2", fps: "280" },
    ],
    highlights: ["Gold-rated PSU from day one", "AM5 upgrade path", "Great raster for the money"],
    description:
      "Team Red through and through. Strong raster performance at 1080p and a platform you can keep for a generation.",
  },
  {
    id: "pulse-5",
    type: "build",
    tier: "budget",
    name: "TIBG Pulse 5",
    tagline: "Best 1080p we sell",
    price: 72199,
    image: "assets/images/pc-budget-2.jpg",
    images: ["assets/images/pc-budget-2.jpg", "assets/images/pc-budget.jpg", "assets/images/part-cooler.jpg"],
    badge: "Best seller",
    resolution: "1080p",
    stock: 11,
    rating: 4.9,
    reviews: 128,
    specs: {
      CPU: "AMD Ryzen 5 9600X",
      GPU: "GeForce RTX 5060 8GB",
      RAM: "16GB DDR5-6000",
      Storage: "1TB Gen4 NVMe",
      Motherboard: "B650",
      PSU: "650W 80+ Gold",
      Cooler: "Dual-tower air",
      Case: "Mesh mid-tower",
    },
    fps: [
      { game: "Black Myth: Wukong", fps: "85" },
      { game: "Valorant", fps: "400+" },
      { game: "GTA VI (est.)", fps: "70" },
    ],
    highlights: ["Our most-ordered budget rig", "9600X stays cool on air", "Ready for high-refresh 1080p"],
    description:
      "The Pulse 5 is the build we put friends on. Fast enough to forget about settings, cheap enough to upgrade the GPU later.",
  },

  /* ───────── Mid-range builds ───────── */
  {
    id: "horizon",
    type: "build",
    tier: "mid",
    name: "TIBG Horizon",
    tagline: "1440p Intel all-rounder",
    price: 114699,
    image: "assets/images/pc-mid.jpg",
    images: ["assets/images/pc-mid.jpg", "assets/images/part-gpu.jpg", "assets/images/part-mb.jpg"],
    badge: "Balanced",
    resolution: "1440p",
    stock: 8,
    rating: 4.7,
    reviews: 63,
    specs: {
      CPU: "Intel Core Ultra 7 265KF",
      GPU: "GeForce RTX 5060 Ti 16GB",
      RAM: "32GB DDR5-6400",
      Storage: "2TB Gen4 NVMe",
      Motherboard: "Z890",
      PSU: "750W 80+ Gold",
      Cooler: "240mm AIO",
      Case: "White dual-chamber",
    },
    fps: [
      { game: "Cyberpunk 2077 RT", fps: "90" },
      { game: "Fortnite", fps: "200" },
      { game: "Adobe Premiere 4K", fps: "smooth" },
    ],
    highlights: ["16GB VRAM headroom", "32GB RAM for creators", "Quiet 240mm AIO"],
    description:
      "Intel’s mid-stack with a 16GB 5060 Ti. The build we recommend when the same machine has to game at night and edit in the morning.",
  },
  {
    id: "nova-7",
    type: "build",
    tier: "mid",
    name: "TIBG Nova 7",
    tagline: "1440p sweet spot",
    price: 127399,
    image: "assets/images/pc-mid-2.jpg",
    images: ["assets/images/pc-mid-2.jpg", "assets/images/pc-mid.jpg", "assets/images/part-cooler.jpg"],
    badge: "Editor’s pick",
    resolution: "1440p",
    stock: 6,
    rating: 4.9,
    reviews: 97,
    specs: {
      CPU: "AMD Ryzen 7 9700X",
      GPU: "GeForce RTX 5070 12GB",
      RAM: "32GB DDR5-6400",
      Storage: "2TB Gen4 NVMe",
      Motherboard: "B850",
      PSU: "750W 80+ Gold",
      Cooler: "240mm AIO",
      Case: "White dual-chamber",
    },
    fps: [
      { game: "Alan Wake 2", fps: "100" },
      { game: "Warzone", fps: "165" },
      { game: "Blender BMW", fps: "fast" },
    ],
    highlights: ["The 1440p recommendation", "RTX 5070 + DLSS 4", "Cable-managed, dust-filtered"],
    description:
      "If you only want one answer for 1440p high-refresh, this is it. 9700X and 5070 stay in balance on every title we bench.",
  },
  {
    id: "vector",
    type: "build",
    tier: "mid",
    name: "TIBG Vector",
    tagline: "X3D for competitive",
    price: 135899,
    image: "assets/images/pc-mid.jpg",
    images: ["assets/images/pc-mid.jpg", "assets/images/part-cpu.jpg", "assets/images/part-ram.jpg"],
    badge: "Esports",
    resolution: "1440p",
    stock: 5,
    rating: 4.8,
    reviews: 72,
    specs: {
      CPU: "AMD Ryzen 7 7800X3D",
      GPU: "GeForce RTX 5070 12GB",
      RAM: "32GB DDR5-6000",
      Storage: "1TB Gen4 NVMe",
      Motherboard: "B650",
      PSU: "750W 80+ Gold",
      Cooler: "Dual-tower air",
      Case: "Mesh mid-tower",
    },
    fps: [
      { game: "CS2", fps: "500+" },
      { game: "Valorant", fps: "500+" },
      { game: "Warzone", fps: "180" },
    ],
    highlights: ["3D V-Cache 1% lows", "Built for 240Hz+", "Still a strong 1440p GPU"],
    description:
      "The 7800X3D is still the cheapest way to buy elite 1% lows. Pair it with a 5070 and you stop thinking about the CPU.",
  },
  {
    id: "flux",
    type: "build",
    tier: "mid",
    name: "TIBG Flux",
    tagline: "Almost 4K, mid price",
    price: 148699,
    image: "assets/images/pc-mid-2.jpg",
    images: ["assets/images/pc-mid-2.jpg", "assets/images/part-gpu.jpg", "assets/images/part-ssd.jpg"],
    badge: "Creator",
    resolution: "1440p",
    stock: 4,
    rating: 4.8,
    reviews: 38,
    specs: {
      CPU: "AMD Ryzen 5 9600X",
      GPU: "GeForce RTX 5070 Ti 16GB",
      RAM: "32GB DDR5-6400",
      Storage: "2TB Gen4 NVMe",
      Motherboard: "B850",
      PSU: "850W 80+ Gold",
      Cooler: "240mm AIO",
      Case: "White dual-chamber",
    },
    fps: [
      { game: "Cyberpunk 2077 PT", fps: "80" },
      { game: "Indiana Jones", fps: "95" },
      { game: "DaVinci 4K", fps: "realtime" },
    ],
    highlights: ["GPU-heavy on purpose", "16GB GDDR7", "850W for a later 5080"],
    description:
      "We spent the budget on the GPU. 5070 Ti at 1440p is overkill in the best way, and it will do 4K with DLSS without feeling cheap.",
  },

  /* ───────── High-end builds ───────── */
  {
    id: "titan-x",
    type: "build",
    tier: "high",
    name: "TIBG Titan X",
    tagline: "4K without the 5090 tax",
    price: 237899,
    image: "assets/images/pc-high.jpg",
    images: ["assets/images/pc-high.jpg", "assets/images/hero.jpg", "assets/images/part-cooler.jpg"],
    badge: "Best 4K value",
    resolution: "4K",
    stock: 5,
    rating: 4.9,
    reviews: 81,
    specs: {
      CPU: "AMD Ryzen 7 9800X3D",
      GPU: "GeForce RTX 5080 16GB",
      RAM: "32GB DDR5-6400",
      Storage: "2TB Gen4 NVMe",
      Motherboard: "X870",
      PSU: "850W 80+ Gold ATX 3.1",
      Cooler: "360mm AIO",
      Case: "Showcase glass ATX",
    },
    fps: [
      { game: "Cyberpunk 2077 PT", fps: "90" },
      { game: "Black Myth: Wukong", fps: "110" },
      { game: "MSFS 2024", fps: "80" },
    ],
    highlights: ["9800X3D + 5080 pairing", "360mm AIO, named PSU", "The 4K build most people should buy"],
    description:
      "This is the high-end we actually recommend. 5080 does 4K ultra with DLSS 4, and the 9800X3D keeps every competitive title pinned.",
  },
  {
    id: "phantom",
    type: "build",
    tier: "high",
    name: "TIBG Phantom",
    tagline: "Intel flagship, 4K",
    price: 271899,
    image: "assets/images/pc-high-2.jpg",
    images: ["assets/images/pc-high-2.jpg", "assets/images/pc-high.jpg", "assets/images/part-mb.jpg"],
    badge: "Creator 4K",
    resolution: "4K",
    stock: 3,
    rating: 4.7,
    reviews: 29,
    specs: {
      CPU: "Intel Core Ultra 9 285K",
      GPU: "GeForce RTX 5080 16GB",
      RAM: "64GB DDR5-7200",
      Storage: "2TB Gen5 NVMe",
      Motherboard: "Z890",
      PSU: "1000W 80+ Platinum",
      Cooler: "360mm AIO",
      Case: "Showcase glass ATX",
    },
    fps: [
      { game: "Cyberpunk 2077 PT", fps: "88" },
      { game: "After Effects 4K", fps: "heavy" },
      { game: "Unreal 5 editor", fps: "fluid" },
    ],
    highlights: ["64GB for huge timelines", "Gen5 boot drive", "Platinum 1000W headroom"],
    description:
      "For people who game and also leave Premiere open for twelve hours. The 285K plus 64GB is the workstation side of this case.",
  },
  {
    id: "apex-ultra",
    type: "build",
    tier: "high",
    name: "TIBG Apex Ultra",
    tagline: "5090, done right",
    price: 382399,
    image: "assets/images/hero.jpg",
    images: ["assets/images/hero.jpg", "assets/images/pc-high.jpg", "assets/images/part-psu.jpg"],
    badge: "Halo",
    resolution: "4K",
    stock: 2,
    rating: 5.0,
    reviews: 18,
    specs: {
      CPU: "AMD Ryzen 9 9950X",
      GPU: "GeForce RTX 5090 32GB",
      RAM: "64GB DDR5-6400",
      Storage: "4TB Gen4 NVMe",
      Motherboard: "X870E",
      PSU: "1200W 80+ Gold ATX 3.1",
      Cooler: "360mm AIO",
      Case: "Full-tower glass",
    },
    fps: [
      { game: "Cyberpunk 2077 PT", fps: "130" },
      { game: "4K path tracing", fps: "yes" },
      { game: "Local LLM 70B", fps: "usable" },
    ],
    highlights: ["32GB GDDR7", "1200W named Gold PSU", "24-hour burn-in on every unit"],
    description:
      "The 5090 build we will actually stand behind: enough PSU, enough cooler, enough airflow. No slim-case nonsense.",
  },
  {
    id: "sovereign",
    type: "build",
    tier: "high",
    name: "TIBG Sovereign",
    tagline: "The last PC you buy",
    price: 424899,
    image: "assets/images/pc-high-2.jpg",
    images: ["assets/images/pc-high-2.jpg", "assets/images/hero.jpg", "assets/images/pc-high.jpg"],
    badge: "Flagship",
    resolution: "4K",
    stock: 1,
    rating: 5.0,
    reviews: 9,
    specs: {
      CPU: "AMD Ryzen 9 9950X3D",
      GPU: "GeForce RTX 5090 32GB",
      RAM: "64GB DDR5-6400",
      Storage: "4TB Gen5 NVMe",
      Motherboard: "X870E",
      PSU: "1200W 80+ Platinum",
      Cooler: "360mm AIO + extra exhaust",
      Case: "Full-tower showcase",
    },
    fps: [
      { game: "Everything maxed", fps: "yes" },
      { game: "8K DLSS", fps: "playable" },
      { game: "Multi-app create", fps: "headroom" },
    ],
    highlights: ["X3D flagship + 5090", "Custom cable kit included", "Priority two-day bench slot"],
    description:
      "We only keep a couple of these on the floor. Dual-CCD X3D for games and creates, 5090 for the pixels, Platinum 1200W so it never gasps.",
  },

  /* ───────── Parts ───────── */
  {
    id: "cpu-9600x",
    type: "part",
    category: "cpu",
    name: "AMD Ryzen 5 9600X",
    tagline: "6-core AM5 gamer",
    price: 16899,
    image: "assets/images/part-cpu.jpg",
    images: ["assets/images/part-cpu.jpg"],
    stock: 22,
    rating: 4.8,
    reviews: 210,
    specs: { Cores: "6 / 12", Boost: "5.4 GHz", Socket: "AM5", TDP: "65W", Cooler: "Not included" },
    highlights: ["Efficient 65W", "Great with a 5060 / 5070"],
    description: "The CPU inside Pulse 5. Enough cores for gaming, cool enough for a dual-tower air cooler.",
  },
  {
    id: "cpu-9700x",
    type: "part",
    category: "cpu",
    name: "AMD Ryzen 7 9700X",
    tagline: "8-core all-rounder",
    price: 25399,
    image: "assets/images/part-cpu.jpg",
    images: ["assets/images/part-cpu.jpg"],
    stock: 16,
    rating: 4.8,
    reviews: 144,
    specs: { Cores: "8 / 16", Boost: "5.5 GHz", Socket: "AM5", TDP: "65W", Cooler: "Not included" },
    highlights: ["The Nova 7 processor", "Streams and games at once"],
    description: "Eight cores, low power, no drama. The mid-range CPU we default to.",
  },
  {
    id: "cpu-9800x3d",
    type: "part",
    category: "cpu",
    name: "AMD Ryzen 7 9800X3D",
    tagline: "Best gaming CPU",
    price: 38199,
    image: "assets/images/part-cpu.jpg",
    images: ["assets/images/part-cpu.jpg"],
    badge: "Hot",
    stock: 6,
    rating: 5.0,
    reviews: 302,
    specs: { Cores: "8 / 16", Boost: "5.2 GHz", Socket: "AM5", Cache: "96MB L3", Cooler: "Not included" },
    highlights: ["3D V-Cache king", "Pairs with 5080 / 5090"],
    description: "If the PC is mostly for games, buy this and stop reading comparison charts.",
  },
  {
    id: "cpu-9950x",
    type: "part",
    category: "cpu",
    name: "AMD Ryzen 9 9950X",
    tagline: "16-core creator",
    price: 46699,
    image: "assets/images/part-cpu.jpg",
    images: ["assets/images/part-cpu.jpg"],
    stock: 8,
    rating: 4.7,
    reviews: 88,
    specs: { Cores: "16 / 32", Boost: "5.7 GHz", Socket: "AM5", TDP: "170W", Cooler: "360mm AIO recommended" },
    highlights: ["Exports, compiles, sims", "Needs a serious cooler"],
    description: "The Apex Ultra CPU. Buy it when your evenings are renders, not just ranked.",
  },
  {
    id: "gpu-5060",
    type: "part",
    category: "gpu",
    name: "GeForce RTX 5060 8GB",
    tagline: "1080p Ultra",
    price: 25399,
    image: "assets/images/part-gpu.jpg",
    images: ["assets/images/part-gpu.jpg"],
    stock: 18,
    rating: 4.6,
    reviews: 190,
    specs: { VRAM: "8GB GDDR7", Power: "170W", Length: "242mm", Ports: "3× DP, 1× HDMI" },
    highlights: ["DLSS 4", "Fits most mid-towers"],
    description: "The Pulse 5 GPU. Honest 1080p ultra, 1440p with DLSS on newer titles.",
  },
  {
    id: "gpu-5060ti",
    type: "part",
    category: "gpu",
    name: "GeForce RTX 5060 Ti 16GB",
    tagline: "1440p VRAM headroom",
    price: 36499,
    image: "assets/images/part-gpu.jpg",
    images: ["assets/images/part-gpu.jpg"],
    stock: 10,
    rating: 4.7,
    reviews: 76,
    specs: { VRAM: "16GB GDDR7", Power: "180W", Length: "260mm", Ports: "3× DP, 1× HDMI" },
    highlights: ["16GB for mods and create", "Horizon’s card"],
    description: "Same class as the 5060 with double the memory. Worth it if you keep games installed for years.",
  },
  {
    id: "gpu-5070",
    type: "part",
    category: "gpu",
    name: "GeForce RTX 5070 12GB",
    tagline: "1440p high-refresh",
    price: 46699,
    image: "assets/images/part-gpu.jpg",
    images: ["assets/images/part-gpu.jpg"],
    badge: "Sweet spot",
    stock: 12,
    rating: 4.8,
    reviews: 221,
    specs: { VRAM: "12GB GDDR7", Power: "250W", Length: "304mm", Ports: "3× DP, 1× HDMI" },
    highlights: ["Nova 7 / Vector GPU", "DLSS 4 + MFG"],
    description: "The card most 1440p players should be on in 2026.",
  },
  {
    id: "gpu-5070ti",
    type: "part",
    category: "gpu",
    name: "GeForce RTX 5070 Ti 16GB",
    tagline: "Near-4K, mid money",
    price: 63699,
    image: "assets/images/part-gpu.jpg",
    images: ["assets/images/part-gpu.jpg"],
    stock: 7,
    rating: 4.8,
    reviews: 94,
    specs: { VRAM: "16GB GDDR7", Power: "300W", Length: "320mm", Ports: "3× DP, 1× HDMI" },
    highlights: ["Flux’s GPU", "Comfortable 4K with DLSS"],
    description: "A half-step below the 5080 and the right upgrade if 1440p already feels too easy.",
  },
  {
    id: "gpu-5080",
    type: "part",
    category: "gpu",
    name: "GeForce RTX 5080 16GB",
    tagline: "Native-feeling 4K",
    price: 84899,
    image: "assets/images/part-gpu.jpg",
    images: ["assets/images/part-gpu.jpg"],
    stock: 5,
    rating: 4.9,
    reviews: 133,
    specs: { VRAM: "16GB GDDR7", Power: "360W", Length: "336mm", Ports: "3× DP, 1× HDMI" },
    highlights: ["Titan X / Phantom GPU", "Needs 850W+"],
    description: "The 4K card we trust. Check your case length and PSU before you drop it in.",
  },
  {
    id: "gpu-5090",
    type: "part",
    category: "gpu",
    name: "GeForce RTX 5090 32GB",
    tagline: "No ceiling",
    price: 169899,
    image: "assets/images/part-gpu.jpg",
    images: ["assets/images/part-gpu.jpg"],
    badge: "Halo",
    stock: 2,
    rating: 4.9,
    reviews: 47,
    specs: { VRAM: "32GB GDDR7", Power: "575W", Length: "358mm", Ports: "3× DP, 1× HDMI" },
    highlights: ["Requires 1000W+ ATX 3.1", "We will not sell it into a weak PSU"],
    description: "Only if the rest of the system can feed it. We refuse undersized PSU combos at the counter.",
  },
  {
    id: "ram-16",
    type: "part",
    category: "ram",
    name: "16GB DDR5-6000 CL30",
    tagline: "2×8GB kit",
    price: 4999,
    image: "assets/images/part-ram.jpg",
    images: ["assets/images/part-ram.jpg"],
    stock: 40,
    rating: 4.7,
    reviews: 310,
    specs: { Capacity: "16GB (2×8)", Speed: "6000 MT/s", Latency: "CL30", Voltage: "1.35V" },
    highlights: ["EXPO / XMP ready"],
    description: "The kit we put in every budget build. Dual-rank enough, tight enough.",
  },
  {
    id: "ram-32",
    type: "part",
    category: "ram",
    name: "32GB DDR5-6400 CL32",
    tagline: "2×16GB kit",
    price: 9299,
    image: "assets/images/part-ram.jpg",
    images: ["assets/images/part-ram.jpg"],
    badge: "Most popular",
    stock: 34,
    rating: 4.9,
    reviews: 401,
    specs: { Capacity: "32GB (2×16)", Speed: "6400 MT/s", Latency: "CL32", Voltage: "1.35V" },
    highlights: ["Chrome + game + Discord"],
    description: "32GB is the new default. Do not cheap this out on a mid-range rig.",
  },
  {
    id: "ram-64",
    type: "part",
    category: "ram",
    name: "64GB DDR5-6400 CL32",
    tagline: "2×32GB kit",
    price: 18599,
    image: "assets/images/part-ram.jpg",
    images: ["assets/images/part-ram.jpg"],
    stock: 15,
    rating: 4.8,
    reviews: 92,
    specs: { Capacity: "64GB (2×32)", Speed: "6400 MT/s", Latency: "CL32", Voltage: "1.35V" },
    highlights: ["VMs, 4K timelines, local AI"],
    description: "What we put in Phantom, Apex, and Sovereign. Overkill for ranked. Perfect for work.",
  },
  {
    id: "ssd-1tb",
    type: "part",
    category: "storage",
    name: "1TB Gen4 NVMe",
    tagline: "7000 MB/s boot drive",
    price: 5899,
    image: "assets/images/part-ssd.jpg",
    images: ["assets/images/part-ssd.jpg"],
    stock: 50,
    rating: 4.8,
    reviews: 520,
    specs: { Capacity: "1TB", Interface: "PCIe 4.0 x4", Read: "7,000 MB/s", NAND: "TLC" },
    highlights: ["DRAM cache", "5-year warranty"],
    description: "The smallest drive we will sell in a complete PC. TLC, not QLC junk.",
  },
  {
    id: "ssd-2tb",
    type: "part",
    category: "storage",
    name: "2TB Gen4 NVMe",
    tagline: "The right size now",
    price: 10999,
    image: "assets/images/part-ssd.jpg",
    images: ["assets/images/part-ssd.jpg"],
    badge: "Recommended",
    stock: 28,
    rating: 4.9,
    reviews: 266,
    specs: { Capacity: "2TB", Interface: "PCIe 4.0 x4", Read: "7,300 MB/s", NAND: "TLC" },
    highlights: ["Shader caches will not evict you"],
    description: "Modern games are huge. 2TB is the floor on mid-range and up.",
  },
  {
    id: "ssd-4tb",
    type: "part",
    category: "storage",
    name: "4TB Gen4 NVMe",
    tagline: "Library, not a slot",
    price: 21199,
    image: "assets/images/part-ssd.jpg",
    images: ["assets/images/part-ssd.jpg"],
    stock: 11,
    rating: 4.8,
    reviews: 70,
    specs: { Capacity: "4TB", Interface: "PCIe 4.0 x4", Read: "7,400 MB/s", NAND: "TLC" },
    highlights: ["Apex Ultra / Sovereign spec"],
    description: "For people who refuse to uninstall. We use the same drive we put in flagship builds.",
  },
  {
    id: "mb-b650",
    type: "part",
    category: "motherboard",
    name: "B650 ATX",
    tagline: "AM5 workhorse",
    price: 12699,
    image: "assets/images/part-mb.jpg",
    images: ["assets/images/part-mb.jpg"],
    stock: 19,
    rating: 4.7,
    reviews: 180,
    specs: { Socket: "AM5", Chipset: "B650", Memory: "DDR5, 4 slots", Networking: "2.5G + Wi-Fi 6E" },
    highlights: ["Four RAM slots", "Two M.2"],
    description: "What we put under 7600 / 9600X / 7800X3D builds. Plenty of VRM for a 65–120W chip.",
  },
  {
    id: "mb-b850",
    type: "part",
    category: "motherboard",
    name: "B850 ATX",
    tagline: "PCIe 5.0 without X870 money",
    price: 16099,
    image: "assets/images/part-mb.jpg",
    images: ["assets/images/part-mb.jpg"],
    stock: 13,
    rating: 4.8,
    reviews: 64,
    specs: { Socket: "AM5", Chipset: "B850", Memory: "DDR5, 4 slots", Networking: "2.5G + Wi-Fi 7" },
    highlights: ["Nova 7 / Flux board"],
    description: "The mid-range default in 2026. Wi-Fi 7, Gen5 GPU slot, no extras you will not use.",
  },
  {
    id: "mb-x870e",
    type: "part",
    category: "motherboard",
    name: "X870E ATX",
    tagline: "Flagship AM5",
    price: 29699,
    image: "assets/images/part-mb.jpg",
    images: ["assets/images/part-mb.jpg"],
    stock: 6,
    rating: 4.8,
    reviews: 41,
    specs: { Socket: "AM5", Chipset: "X870E", Memory: "DDR5, 4 slots", Networking: "5G + Wi-Fi 7" },
    highlights: ["Apex / Sovereign board", "Serious VRM"],
    description: "For 9950X-class chips and people who want every M.2 slot filled.",
  },
  {
    id: "psu-650",
    type: "part",
    category: "psu",
    name: "650W 80+ Gold",
    tagline: "Budget / 5060 class",
    price: 6699,
    image: "assets/images/part-psu.jpg",
    images: ["assets/images/part-psu.jpg"],
    stock: 24,
    rating: 4.7,
    reviews: 155,
    specs: { Wattage: "650W", Rating: "80+ Gold", Modular: "Fully", Standard: "ATX 3.1" },
    highlights: ["Native 12V-2×6"],
    description: "Named-brand Gold. We do not ship no-name units in complete PCs.",
  },
  {
    id: "psu-850",
    type: "part",
    category: "psu",
    name: "850W 80+ Gold",
    tagline: "5080 ready",
    price: 10099,
    image: "assets/images/part-psu.jpg",
    images: ["assets/images/part-psu.jpg"],
    badge: "Safe pick",
    stock: 17,
    rating: 4.9,
    reviews: 203,
    specs: { Wattage: "850W", Rating: "80+ Gold", Modular: "Fully", Standard: "ATX 3.1" },
    highlights: ["Titan X spec", "Headroom for a later GPU"],
    description: "The PSU we put in anything with a 5070 Ti or 5080. Do not undersize this.",
  },
  {
    id: "psu-1200",
    type: "part",
    category: "psu",
    name: "1200W 80+ Platinum",
    tagline: "5090, no asterisk",
    price: 19499,
    image: "assets/images/part-psu.jpg",
    images: ["assets/images/part-psu.jpg"],
    stock: 8,
    rating: 4.9,
    reviews: 58,
    specs: { Wattage: "1200W", Rating: "80+ Platinum", Modular: "Fully", Standard: "ATX 3.1" },
    highlights: ["Apex / Sovereign spec"],
    description: "If you are buying a 5090 from us, this is the floor.",
  },
  {
    id: "cooler-air",
    type: "part",
    category: "cooler",
    name: "Dual-tower air cooler",
    tagline: "Silent 65–120W",
    price: 3299,
    image: "assets/images/part-cooler.jpg",
    images: ["assets/images/part-cooler.jpg"],
    stock: 30,
    rating: 4.6,
    reviews: 240,
    specs: { Type: "Air", Heatpipes: "6", TDP: "220W", Height: "158mm" },
    highlights: ["No pump to fail"],
    description: "What we use on Pulse, Spark, and Vector. Cheaper and often quieter than a cheap AIO.",
  },
  {
    id: "cooler-240",
    type: "part",
    category: "cooler",
    name: "240mm AIO",
    tagline: "Mid-range default",
    price: 7599,
    image: "assets/images/part-cooler.jpg",
    images: ["assets/images/part-cooler.jpg"],
    stock: 14,
    rating: 4.7,
    reviews: 99,
    specs: { Type: "AIO liquid", Radiator: "240mm", Fans: "2× 120mm", Socket: "AM5 / LGA 1851" },
    highlights: ["Nova / Horizon / Flux"],
    description: "A quiet 240 is enough for every mid-range chip we sell.",
  },
  {
    id: "cooler-360",
    type: "part",
    category: "cooler",
    name: "360mm AIO",
    tagline: "High-end / 170W chips",
    price: 11799,
    image: "assets/images/part-cooler.jpg",
    images: ["assets/images/part-cooler.jpg"],
    stock: 11,
    rating: 4.8,
    reviews: 77,
    specs: { Type: "AIO liquid", Radiator: "360mm", Fans: "3× 120mm", Socket: "AM5 / LGA 1851" },
    highlights: ["Required on 9950X / 285K"],
    description: "The cooler on Titan X and everything above. We mount it as intake up top unless the case says otherwise.",
  },
  {
    id: "case-mesh",
    type: "part",
    category: "case",
    name: "Mesh mid-tower",
    tagline: "Airflow first",
    price: 6699,
    image: "assets/images/part-case.jpg",
    images: ["assets/images/part-case.jpg", "assets/images/pc-budget.jpg"],
    stock: 20,
    rating: 4.7,
    reviews: 188,
    specs: { Form: "ATX mid-tower", GPU: "up to 380mm", Radiator: "360mm front", Glass: "Tempered side" },
    highlights: ["Budget and esports builds"],
    description: "Mesh front, dust filters, room for a long GPU. The case we trust when looks come second to temps.",
  },
  {
    id: "case-vision",
    type: "part",
    category: "case",
    name: "Dual-chamber ATX",
    tagline: "Clean cable side",
    price: 10999,
    image: "assets/images/part-case.jpg",
    images: ["assets/images/part-case.jpg", "assets/images/pc-mid.jpg"],
    stock: 9,
    rating: 4.8,
    reviews: 61,
    specs: { Form: "ATX dual-chamber", GPU: "up to 420mm", Radiator: "360mm side", Glass: "Panoramic" },
    highlights: ["Mid-range looker"],
    description: "The white dual-chamber on Nova and Flux. PSU and cables hide in the back chamber.",
  },
  {
    id: "case-showcase",
    type: "part",
    category: "case",
    name: "Showcase full-tower",
    tagline: "Flagship glass",
    price: 16099,
    image: "assets/images/part-case.jpg",
    images: ["assets/images/part-case.jpg", "assets/images/pc-high.jpg"],
    stock: 6,
    rating: 4.9,
    reviews: 34,
    specs: { Form: "Full-tower", GPU: "up to 450mm", Radiator: "360mm top + side", Glass: "Panoramic" },
    highlights: ["Titan / Apex / Sovereign"],
    description: "Built to show the 360 and the 5090, not hide them. Excellent intake, no aquarium gimmicks.",
  },
];

const REVIEWS = [
  {
    name: "Abdul Ahad",
    meta: "TIBG Pulse 5 · Kanpur",
    stars: 5,
    text: "Ordered on a Tuesday, playing Valorant Thursday night. Cables are cleaner than anything I have built myself.",
  },
  {
    name: "Jordan Hale",
    meta: "TIBG Nova 7 · Austin",
    stars: 5,
    text: "1440p on a 27-inch and it just sits at 160. Support walked me through BIOS EXPO in ten minutes.",
  },
  {
    name: "Priya Shah",
    meta: "TIBG Titan X · Brooklyn",
    stars: 5,
    text: "I was ready to overpay a boutique shop. Titan X is quieter than my old 3080 tower and actually uses a named PSU.",
  },
  {
    name: "Luis Ortega",
    meta: "RTX 5070 + B850 · parts",
    stars: 4,
    text: "Bought parts à la carte. Everything arrived packed like they expected me to return it, which I did not.",
  },
];

const FAQS = [
  {
    q: "Are these real prebuilts or just a parts list?",
    a: "Every complete PC is assembled, cable-managed, and burned in for 24 hours on our bench in San Francisco. You get Windows 11 Pro, drivers, and a photo of your unit before it ships.",
  },
  {
    q: "What is the warranty?",
    a: "Three years on labor and assembly, two years on branded parts (or the manufacturer’s warranty, whichever is longer). Accidental damage is not covered. We handle the RMA so you do not have to.",
  },
  {
    q: "Can I customize a prebuilt?",
    a: "Yes. More RAM, a larger SSD, a different case color, or a GPU bump. Email the build name and we will quote it the same day. Custom quotes usually ship within 5–7 business days.",
  },
  {
    q: "Do you ship nationwide?",
    a: "Yes. Free ground on prebuilts over ₹99,999. Parts ship from the bench or a partner warehouse, usually in two business days.",
  },
  {
    q: "What is your return policy?",
    a: "14 days on unopened parts. Prebuilts can come back within 14 days if they are in original condition — a 5% restock applies because we re-test. DOA units are swapped at our cost.",
  },
  {
    q: "Will you sell me a 5090 with a 650W PSU?",
    a: "No. We will tell you why and sell you the PSU you actually need. That is the whole point of the shop.",
  },
];

const PROCESS = [
  { n: "01", title: "Spec", text: "You pick a tier or a parts list. We sanity-check PSU, cooler, and case clearance." },
  { n: "02", title: "Build", text: "Assembled on the Folsom bench. Custom cables on high-end, tidy stock cables on budget." },
  { n: "03", title: "Burn-in", text: "24 hours of CPU + GPU load, then a game pass. You get a photo and the log." },
  { n: "04", title: "Ship", text: "Double-boxed, GPU braced, tracked. Local pickup the same week if you want it." },
];
