/* Kunafa Mahal — brand, menu, and store config
   Details taken from kunafamahal.in, Zomato, and the Hazratganj listing. */
window.KM = window.KM || {};

KM.brand = {
  name: "Kunafa Mahal",
  tagline: "Indulge in Royal Flavors",
  subtitle: "Experience luxury with every bite of our gourmet treats.",
  description:
    "Kunafa Mahal is a modern QSR café inspired by Middle Eastern royalty. We serve freshly made kunafa and specialty coffee in a warm, elegant setting. Every bite blends tradition with contemporary taste.",
  heritage:
    "At Kunafa Mahal, we believe in celebrating the rich culinary traditions of the Middle East. Our heritage is reflected in every dish, combining royal flavors with modern dining experiences.",
  phone: "+917307097771",
  phoneDisplay: "+91 73070 97771",
  whatsapp: "https://wa.me/917307097771",
  email: "hello@kunafamahal.in",
  website: "https://kunafamahal.in/",
  zomato: "https://www.zomato.com/lucknow/kunafa-mahal-hazratganj",
  maps: "https://maps.app.goo.gl/fgw6T6rt8KAGpr797",
  mapsEmbed:
    "https://maps.google.com/maps?q=Shop%204%2C%20New%20Market%2C%20Zone%202%2C%20Near%20Multilevel%20Parking%2C%20Hazratganj%2C%20Lucknow&z=16&output=embed",
  address: "Shop 4, New Market, Zone 2, Near Multilevel Parking",
  area: "Hazratganj",
  city: "Lucknow",
  state: "Uttar Pradesh",
  pincode: "226001",
  fullAddress:
    "Shop 4, New Market, Zone 2, Near Multilevel Parking, Mahatma Gandhi Marg, Hazratganj, Lucknow, Uttar Pradesh 226001",
  hours: "12:00 pm – 11:45 pm",
  hoursNote: "Open all seven days. Kitchen last call 11:30 pm.",
  fssai: "22725731000240",
  costForTwo: 500,
  ratingDining: 3.4,
  ratingDelivery: 4.2,
  ratingCount: 233,
  vegOnly: true,
  cuisines: ["Desserts", "Arabic", "Café", "Coffee", "Lebanese", "Middle Eastern"],
};

KM.hours = [
  { day: "Monday", open: "12:00", close: "23:45" },
  { day: "Tuesday", open: "12:00", close: "23:45" },
  { day: "Wednesday", open: "12:00", close: "23:45" },
  { day: "Thursday", open: "12:00", close: "23:45" },
  { day: "Friday", open: "12:00", close: "23:45" },
  { day: "Saturday", open: "12:00", close: "23:45" },
  { day: "Sunday", open: "12:00", close: "23:45" },
];

KM.delivery = {
  minOrder: 199,
  fee: 49,
  freeAbove: 599,
  packaging: 10,
  gstRate: 0.05,
  etaMin: 25,
  etaMax: 45,
  radiusNote: "We deliver across central Lucknow. Enter your area at checkout.",
  zones: [
    { id: "hazratganj", name: "Hazratganj", eta: 20, fee: 29 },
    { id: "aminabad", name: "Aminabad", eta: 25, fee: 39 },
    { id: "gomti", name: "Gomti Nagar", eta: 35, fee: 49 },
    { id: "indira", name: "Indira Nagar", eta: 30, fee: 49 },
    { id: "aliganj", name: "Aliganj", eta: 35, fee: 49 },
    { id: "mahanagar", name: "Mahanagar", eta: 28, fee: 39 },
    { id: "alambagh", name: "Alambagh", eta: 40, fee: 59 },
    { id: "husainabad", name: "Husainabad / Chowk", eta: 30, fee: 39 },
    { id: "gomti2", name: "Gomti Nagar Extension", eta: 45, fee: 69 },
    { id: "ashiyana", name: "Ashiyana / LDA", eta: 45, fee: 69 },
    { id: "other", name: "Other Lucknow area", eta: 50, fee: 79 },
  ],
};

KM.loyalty = {
  name: "Loyalty points",
  perOrder: 100,
  rupeesPer100: 50,
  rupees(points) { return Math.floor((Number(points) || 0) * this.rupeesPer100 / 100); },
  points(rupees) { return Math.floor((Number(rupees) || 0) * 100 / this.rupeesPer100); },
};

KM.promos = {
  ROYAL50: { type: "flat", value: 50, min: 399, label: "₹50 off above ₹399" },
  KUNAFA10: { type: "percent", value: 10, min: 499, label: "10% off above ₹499" },
  WELCOME: { type: "flat", value: 80, min: 449, label: "₹80 off first order" },
  PALACE: { type: "flat", value: 120, min: 899, label: "₹120 off party boxes" },
};

KM.categories = [
  { id: "signature", name: "Signature Kunafa", blurb: "The house classics, poured warm." },
  { id: "fusion", name: "Indo-Fusion", blurb: "Lucknow sweets, rewritten in kataifi." },
  { id: "exotic", name: "Exotic Kunafas", blurb: "Chocolate, fruit, and lotus silk." },
  { id: "tubs", name: "Kunafa Tubs", blurb: "Layered cups made for takeaway." },
  { id: "bombs", name: "Kunafa Bombs", blurb: "Crack, scoop, repeat." },
  { id: "combos", name: "Combos & Boxes", blurb: "Shareable royal sets." },
  { id: "bites", name: "Bites & Bars", blurb: "Truffles, cones, Dubai bars." },
  { id: "arabic", name: "Arabic Specials", blurb: "Koshari, umm ali, loua, habba." },
  { id: "shakes", name: "Shakes", blurb: "Dessert in a branded bottle." },
  { id: "coffee", name: "Coffee Essentials", blurb: "Qahwa to mocha." },
  { id: "specials", name: "House Specials", blurb: "Added from the palace kitchen." },
];

KM.menu = [
  /* Signature */
  {
    id: "nabulsi",
    name: "Royal Nabulsi Kunafa",
    cat: "signature",
    price: 279,
    popular: true,
    tag: "Signature",
    img: "assets/dishes/nabulsi.jpg",
    desc: "Soft, stretchy cheese wrapped in crispy kunafa, finished with a gentle pour of warm aromatic syrup — truly Lucknow-royal.",
  },
  {
    id: "gul-kunafa",
    name: "Gul-Kunafa",
    cat: "signature",
    price: 269,
    img: "assets/dishes/nabulsi.jpg",
    desc: "Kunafa kissed with rose essence, scented like old Lucknow streets in spring.",
  },
  {
    id: "ashta",
    name: "Ashta-E-Malai Kunafa",
    cat: "signature",
    price: 289,
    img: "assets/dishes/lucknowi-malai.jpg",
    desc: "A silky ashta cream centre in crunchy kunafa strands — smooth, subtle and indulgent.",
  },
  {
    id: "pista-badami",
    name: "Pista-Badami Royale Kunafa",
    cat: "signature",
    price: 329,
    popular: true,
    img: "assets/dishes/pista-badami.jpg",
    desc: "Rich pistachio crème layered with golden kunafa for a luxurious nutty bite.",
  },
  {
    id: "nut-salt",
    name: "Nut Salt N Soot Kunafa",
    cat: "signature",
    price: 299,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "Warm molten Nutella wrapped in kunafa — soft, gooey, and a little salty.",
  },

  /* Indo-Fusion */
  {
    id: "gulab",
    name: "Gulab Jamun Bliss Kunafa",
    cat: "fusion",
    price: 299,
    popular: true,
    tag: "Lucknow",
    img: "assets/dishes/gulab-jamun.jpg",
    desc: "Classic gulab jamun folded into traditional Middle Eastern kunafa, soaked in saffron syrup.",
  },
  {
    id: "ras-royale",
    name: "Ras Royale Kunafa",
    cat: "fusion",
    price: 309,
    img: "assets/dishes/lucknowi-malai.jpg",
    desc: "Rasmalai-inspired kunafa with kesar milk and pistachio crumble.",
  },
  {
    id: "lucknowi",
    name: "Lucknowi Malai Kunafa",
    cat: "fusion",
    price: 319,
    popular: true,
    img: "assets/dishes/lucknowi-malai.jpg",
    desc: "Rich cream kunafa layered with rabdi — the heart of Awadhi indulgence.",
  },
  {
    id: "paan",
    name: "Paan-E-Khaas Kunafa",
    cat: "fusion",
    price: 289,
    img: "assets/dishes/paan-khaas.jpg",
    desc: "Betel leaf-infused kunafa with a rose and gulkand centre.",
  },

  /* Exotic */
  {
    id: "nutella-silk",
    name: "Nutella Silk Kunafa",
    cat: "exotic",
    price: 299,
    popular: true,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "Warm molten Nutella wrapped in kunafa — soft, gooey, crazy addictive.",
  },
  {
    id: "triple-choco",
    name: "Triple Chocolate Kunafa",
    cat: "exotic",
    price: 319,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "A rich hybrid dessert that layers dark, milk and white chocolate through golden kunafa.",
  },
  {
    id: "aam",
    name: "Aam-E-Bahaar Kunafa",
    cat: "exotic",
    price: 309,
    tag: "Seasonal",
    img: "assets/dishes/aam-e-bahaar.jpg",
    desc: "Ripe mango purée whipped with cream inside a fresh crunchy kunafa frame.",
  },
  {
    id: "caramel",
    name: "Caramel Noor Kunafa",
    cat: "exotic",
    price: 289,
    img: "assets/dishes/lotus-silk.jpg",
    desc: "Buttery caramel folded through crispy kunafa and finished with a warm syrup glaze.",
  },
  {
    id: "blueberry",
    name: "Blueberry Shab-E-Jamun",
    cat: "exotic",
    price: 299,
    img: "assets/dishes/blueberry.jpg",
    desc: "Tart blueberry coulis meets velvety cream for a bright, refreshing finish.",
  },
  {
    id: "choco-lava",
    name: "Choco-Lava Kunafa",
    cat: "exotic",
    price: 309,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "Dark chocolate lava erupts inside delicate kunafa threads — pure drama in every spoon.",
  },
  {
    id: "lotus-silk",
    name: "Lotus Silk Kunafa",
    cat: "exotic",
    price: 299,
    popular: true,
    img: "assets/dishes/lotus-silk.jpg",
    desc: "Smooth lotus cream folded into crispy kunafa layers for the perfect dreamy spoon.",
  },

  /* Tubs */
  {
    id: "mini-cheese-tub",
    name: "Mini Cheese Tub",
    cat: "tubs",
    price: 199,
    img: "assets/dishes/pista-tub.jpg",
    desc: "Tiny cup, stretchy cheese, instant happiness.",
  },
  {
    id: "nutella-tub",
    name: "Nutella Shot Tub",
    cat: "tubs",
    price: 349,
    img: "assets/dishes/pista-tub.jpg",
    desc: "A large-format dessert tub designed to emulate the taste of a Nutella shot — layered and shareable.",
  },
  {
    id: "tiramisu-tub",
    name: "Kunafa Tiramisu Tub",
    cat: "tubs",
    price: 369,
    img: "assets/dishes/pista-tub.jpg",
    desc: "Italian tiramisu layered with Middle-Eastern kunafa — the city of nawabs meets Rome.",
  },
  {
    id: "lotus-tub",
    name: "Lotus Velvet Tub",
    cat: "tubs",
    price: 349,
    img: "assets/dishes/pista-tub.jpg",
    desc: "Smooth lotus cream layered with light kunafa crumbs.",
  },
  {
    id: "pista-tub",
    name: "Pista Royale Tub",
    cat: "tubs",
    price: 369,
    img: "assets/dishes/pista-tub.jpg",
    desc: "Rich creamy saffron and pistachio dessert layered with cake, cream and kunafa.",
  },

  /* Bombs */
  {
    id: "choco-bomb",
    name: "Choco Indulge Kunafa Bomb",
    cat: "bombs",
    price: 279,
    img: "assets/dishes/kunafa-bomb.jpg",
    desc: "Crispy buttery kunafa sphere with a molten chocolate heart.",
  },
  {
    id: "pista-bomb",
    name: "Pistachio Kunafa Bomb",
    cat: "bombs",
    price: 299,
    popular: true,
    img: "assets/dishes/kunafa-bomb.jpg",
    desc: "Crispy shredded kunafa, sweet pistachio paste and creamy cheese — break and share.",
  },

  /* Combos */
  {
    id: "mini-combo",
    name: "Assorted Mini Kunafa Combo",
    cat: "combos",
    price: 399,
    popular: true,
    img: "assets/dishes/mini-kunafas.jpg",
    desc: "Three bite-sized kunafas — crisp shredded phyllo layered with our best-seller fillings.",
  },
  {
    id: "fifty",
    name: "50-50 Kunafa",
    cat: "combos",
    price: 449,
    img: "assets/dishes/mini-kunafas.jpg",
    desc: "A dual plate: pick any two half-kunafas and share the contrast.",
  },
  {
    id: "experience",
    name: "The Kunafa Experience Box",
    cat: "combos",
    price: 799,
    tag: "Gift",
    img: "assets/dishes/mini-kunafas.jpg",
    desc: "A luxurious assortment of chocolate, caramel, biscoff and malai kunafas.",
  },
  {
    id: "party",
    name: "Royal Kunafa Party Box",
    cat: "combos",
    price: 1299,
    tag: "Serves 4",
    img: "assets/dishes/mini-kunafas.jpg",
    desc: "Signature Nabulsi, pistachio truffle, kunafa tub and shakes — complete palace indulgence.",
  },
  {
    id: "me-classic",
    name: "Middle Eastern Classic",
    cat: "combos",
    price: 399,
    img: "assets/dishes/qahwa.jpg",
    desc: "Traditional Nabulsi kunafa served with hot Arabic qahwa and dates.",
  },
  {
    id: "pista-affair",
    name: "Kunafa Pistachio Affair",
    cat: "combos",
    price: 499,
    img: "assets/dishes/kunafa-bomb.jpg",
    desc: "Break the pistachio kunafa bomb, sip the pista kunafa milkshake.",
  },
  {
    id: "tiramisu-brew",
    name: "Tiramisu & Brew Combo",
    cat: "combos",
    price: 449,
    img: "assets/dishes/pista-tub.jpg",
    desc: "Kunafa tiramisu tub served with a barista-style cappuccino.",
  },
  {
    id: "truffle-duo",
    name: "Truffle Cappuccino Duo",
    cat: "combos",
    price: 399,
    img: "assets/dishes/qahwa.jpg",
    desc: "Pistachio truffles paired with a smooth cappuccino.",
  },

  /* Bites */
  {
    id: "hazel-truffle-4",
    name: "Hazelnut Truffle Bites (4)",
    cat: "bites",
    price: 249,
    img: "assets/dishes/pistachio-bar.jpg",
    desc: "Crunchy Nutella core with kunafa flakes and roasted hazelnuts.",
  },
  {
    id: "pista-truffle-4",
    name: "Pistachio Truffle Bites (4)",
    cat: "bites",
    price: 269,
    img: "assets/dishes/pistachio-bar.jpg",
    desc: "Creamy pistachio truffles in a chocolate shell, crushed pistachio garnish.",
  },
  {
    id: "hazel-mini-bar",
    name: "Hazelnut Luxe Mini Bar",
    cat: "bites",
    price: 199,
    img: "assets/dishes/pistachio-bar.jpg",
    desc: "Fusion mini chocolate bar with caramelised kunafa and hazelnut praline.",
  },
  {
    id: "pista-bar",
    name: "Pistachio Luxe Kunafa Bar",
    cat: "bites",
    price: 349,
    popular: true,
    tag: "Dubai",
    img: "assets/dishes/pistachio-bar.jpg",
    desc: "Dubai-inspired bar — milk chocolate, crunchy kunafa pastry and pistachio cream.",
  },
  {
    id: "cones",
    name: "Assorted Kunafa Cones",
    cat: "bites",
    price: 329,
    img: "assets/dishes/kunafa-cones.jpg",
    desc: "Three chocolate-dipped kunafa cones — milk, dark and white, packed with nuts.",
  },

  /* Arabic specials */
  {
    id: "rose-koshari",
    name: "Royal Rose Velvet Koshari",
    cat: "arabic",
    price: 329,
    img: "assets/dishes/paan-khaas.jpg",
    desc: "Delicately infused with aromatic rose — royal Middle Eastern sweetness.",
  },
  {
    id: "pista-koshari",
    name: "Pista-Biscoff Crunch Koshari",
    cat: "arabic",
    price: 349,
    img: "assets/dishes/lotus-silk.jpg",
    desc: "Premium pistachio meets caramelised Biscoff in a bold Arabian crunch.",
  },
  {
    id: "choco-koshari",
    name: "Triple Chocolate Indulgence Koshari",
    cat: "arabic",
    price: 349,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "A decadent trio of chocolates layered in a velvety Dubai-inspired texture.",
  },
  {
    id: "hazel-koshari",
    name: "Hazel-Kinder Koshari",
    cat: "arabic",
    price: 339,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "Hazelnut cream and smooth chocolate, crafted with a modern Arabian finish.",
  },
  {
    id: "umm-ali",
    name: "Kesari Umm Ali",
    cat: "arabic",
    price: 279,
    img: "assets/dishes/lucknowi-malai.jpg",
    desc: "Traditional Egyptian pastry pudding, crispy layers soaked in rich almond-saffron milk.",
  },
  {
    id: "choco-kabsa",
    name: "Choco Empire Kabsa",
    cat: "arabic",
    price: 329,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "An intense cocoa dessert layered with richness, inspired by Dubai-style indulgence.",
  },
  {
    id: "falooda-loua",
    name: "Falooda Loua",
    cat: "arabic",
    price: 249,
    img: "assets/dishes/blueberry.jpg",
    desc: "A refreshing blend of fruits and falooda textures, inspired by vibrant Middle Eastern glasses.",
  },
  {
    id: "blue-loua",
    name: "Blueberry Delight Loua",
    cat: "arabic",
    price: 269,
    img: "assets/dishes/blueberry.jpg",
    desc: "Smooth creamy dessert with a sweet-tangy blueberry burst.",
  },
  {
    id: "habba",
    name: "Pistachio Cocoa Habba Cake",
    cat: "arabic",
    price: 749,
    tag: "Celebrate",
    img: "assets/dishes/pista-tub.jpg",
    desc: "Soft chocolate cake layered with pistachio richness — our celebration habba.",
  },
  {
    id: "salankatia-pista",
    name: "Pista Dream Salankatia",
    cat: "arabic",
    price: 529,
    popular: true,
    img: "assets/dishes/pista-badami.jpg",
    desc: "A pistachio-forward creation with smooth, rich layers — for true lovers of Arabian flavours.",
  },
  {
    id: "salankatia-nuts",
    name: "Nuts Overload Salankatia",
    cat: "arabic",
    price: 549,
    img: "assets/dishes/pista-badami.jpg",
    desc: "Crunchy nuts blended with creamy richness, inspired by traditional Arabic dessert textures.",
  },
  {
    id: "salankatia-trio",
    name: "Signature Trio Salankatia",
    cat: "arabic",
    price: 579,
    img: "assets/dishes/mini-kunafas.jpg",
    desc: "A luxurious trio of flavours on one platter of lavish dessert layers.",
  },
  {
    id: "salankatia-mango",
    name: "Ras-Bhari Mango Salankatia",
    cat: "arabic",
    price: 549,
    img: "assets/dishes/aam-e-bahaar.jpg",
    desc: "Royal Indian rasmalai and tropical mango, reimagined with a Middle Eastern finish.",
  },
  {
    id: "salankatia-nutella",
    name: "Nutella-Pista Affair Salankatia",
    cat: "arabic",
    price: 569,
    img: "assets/dishes/nutella-silk.jpg",
    desc: "Warm, soft layers filled with molten Nutella and topped with pistachio.",
  },

  /* Shakes */
  {
    id: "shake-nutella",
    name: "Nutella Kunafa Milkshake",
    cat: "shakes",
    price: 249,
    img: "assets/dishes/biscoff-shake.jpg",
    desc: "Chocolate-hazelnut shake blended with Middle Eastern dessert textures.",
  },
  {
    id: "shake-biscoff",
    name: "Biscoff Kunafa Milkshake",
    cat: "shakes",
    price: 249,
    popular: true,
    img: "assets/dishes/biscoff-shake.jpg",
    desc: "Vanilla ice cream, milk and Biscoff, blended with roasted kunafa strands.",
  },
  {
    id: "shake-pista",
    name: "Pista Kunafa Milkshake",
    cat: "shakes",
    price: 269,
    img: "assets/dishes/biscoff-shake.jpg",
    desc: "Sweet pistachio cream, ice cream and crispy kunafa in a branded bottle.",
  },
  {
    id: "shake-choco",
    name: "Chocolate Kunafa Milkshake",
    cat: "shakes",
    price: 249,
    img: "assets/dishes/biscoff-shake.jpg",
    desc: "Rich chocolate, creamy ice cream and the signature kunafa crunch.",
  },
  {
    id: "viet",
    name: "Vietnamese Cold Coffee",
    cat: "shakes",
    price: 229,
    img: "assets/dishes/biscoff-shake.jpg",
    desc: "Bold dark-roasted coffee balanced with sweet condensed milk over ice.",
  },

  /* Coffee */
  {
    id: "cranberry-brew",
    name: "Cranberry Cold Brew",
    cat: "coffee",
    price: 219,
    img: "assets/dishes/qahwa.jpg",
    desc: "Smooth low-acidity cold brew with tart-sweet cranberry.",
  },
  {
    id: "cold-coffee",
    name: "Classic Cold Coffee",
    cat: "coffee",
    price: 189,
    img: "assets/dishes/biscoff-shake.jpg",
    desc: "Creamy, frothy blended coffee — chilled and simple.",
  },
  {
    id: "qahwa",
    name: "Hot Qahwa with Dates",
    cat: "coffee",
    price: 169,
    img: "assets/dishes/qahwa.jpg",
    desc: "Arabic coffee ritual — a symbol of Middle Eastern hospitality, served with dates.",
  },
  {
    id: "americano-hot",
    name: "Hot Americano",
    cat: "coffee",
    price: 149,
    img: "assets/dishes/qahwa.jpg",
    desc: "Bold espresso lengthened with hot water.",
  },
  {
    id: "americano-iced",
    name: "Iced Americano",
    cat: "coffee",
    price: 159,
    img: "assets/dishes/qahwa.jpg",
    desc: "Hot espresso poured over cold water and ice.",
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    cat: "coffee",
    price: 179,
    img: "assets/dishes/qahwa.jpg",
    desc: "Equal parts espresso, steamed milk and foam.",
  },
  {
    id: "latte",
    name: "Latte",
    cat: "coffee",
    price: 189,
    img: "assets/dishes/qahwa.jpg",
    desc: "A shot of espresso with plenty of steamed milk.",
  },
  {
    id: "mocha",
    name: "Café Mocha",
    cat: "coffee",
    price: 199,
    img: "assets/dishes/qahwa.jpg",
    desc: "Espresso, steamed milk and chocolate syrup.",
  },
];

KM.reviews = [
  {
    name: "Anurag Gautam",
    stars: 5,
    text: "I tried the dry-fruit kunafa and it was a must-eat. Warm, stretchy, properly royal.",
    source: "Dining · Hazratganj",
  },
  {
    name: "Junaid Alam",
    stars: 5,
    text: "Came for Nabulsi, stayed for the pistachio bomb and qahwa. Service is quick.",
    source: "Dining · Hazratganj",
  },
  {
    name: "Meher Siddiqui",
    stars: 5,
    text: "Aam-E-Bahaar in mango season is dangerous. Ordered again the same evening.",
    source: "Delivery · Gomti Nagar",
  },
  {
    name: "Ritika Banerjee",
    stars: 4,
    text: "Pretty café, pure veg, and the branded milkshake bottles are a nice touch for gifting.",
    source: "Dining · Hazratganj",
  },
];

KM.item = (id) => KM.menu.find((i) => i.id === id);
KM.byCat = (cat) => KM.menu.filter((i) => i.cat === cat);
KM.popular = () => KM.menu.filter((i) => i.popular);
KM.loadMenu = async () => {
  try {
    const data = await KM.api.get("/api/menu");
    if (Array.isArray(data.items) && data.items.length) KM.menu = data.items;
  } catch { /* keep the built-in menu if the desk is offline */ }
};
