"""Load the already-verified NYC dental offices into the database."""

from __future__ import annotations

from store import init, upsert_lead

SEED = [
    {
        "name": "Fort Washington Dental Associates",
        "contact_name": "Dr. Dennis N. Morea, DDS",
        "phone": "(212) 928-9000",
        "address": "130 Fort Washington Avenue",
        "city": "New York",
        "state": "NY",
        "zip": "10032",
        "borough": "Manhattan",
        "neighborhood": "Washington Heights",
        "online_presence": "Healthgrades, WebMD — no practice site found",
        "notes": "Columbia CDM alumnus. No official office website located.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Gary L. Thomas, DDS",
        "contact_name": "Dr. Gary L. Thomas, DDS",
        "phone": "(718) 230-0203",
        "address": "304 DeKalb Avenue",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11205",
        "borough": "Brooklyn",
        "neighborhood": "Clinton Hill / Fort Greene",
        "online_presence": "Yelp, WebMD, DentalPlans — no practice site found",
        "notes": "Solo practice. Yelp has no Visit Website link.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Lidiya Yelskaya General Dentistry",
        "contact_name": "Dr. Lidiya Yelskaya, DDS",
        "phone": "(718) 676-9500",
        "address": "1625 Emmons Avenue, Suite AA",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11235",
        "borough": "Brooklyn",
        "neighborhood": "Sheepshead Bay / Brighton Beach",
        "online_presence": "Yelp, Healthgrades, MapQuest — no practice site found",
        "notes": "Also listed as R & J Dental at this address.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Family Smiles Dental / Michael J. Mand, DDS PC",
        "contact_name": "Dr. Michael J. Mand, DDS",
        "phone": "(718) 435-3726",
        "address": "502 39th Street, Suite 2F",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11232",
        "borough": "Brooklyn",
        "neighborhood": "Sunset Park",
        "online_presence": "NPI, WebMD, MapQuest — NPI website field is blank",
        "notes": "Fax (718) 435-5855. Attending at Jamaica Hospital dental residency.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Yelena Ustinina, DDS, PC",
        "contact_name": "Dr. Yelena Ustinina, DDS",
        "phone": "(347) 492-6801",
        "address": "2084 East 17th Street",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11229",
        "borough": "Brooklyn",
        "neighborhood": "Sheepshead Bay / Midwood",
        "online_presence": "Yelp, Healthgrades, MapQuest — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Vladimir Blustin, DDS",
        "contact_name": "Dr. Vladimir Blustin, DDS",
        "phone": "(718) 692-0729",
        "address": "1916 Avenue K, Apt 2K",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11230",
        "borough": "Brooklyn",
        "neighborhood": "Midwood",
        "online_presence": "WebMD and discount-plan directories only",
        "notes": "Russian-speaking dentist.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Jean-Edouard Fayette, DDS",
        "contact_name": "Dr. Jean-Edouard Fayette, DDS",
        "phone": "(718) 953-7639",
        "address": "456 Schenectady Avenue, Apt 1P",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11203",
        "borough": "Brooklyn",
        "neighborhood": "Crown Heights / East Flatbush",
        "online_presence": "WebMD, Vitals, FindATopDoc — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Allan Lebovitz, DDS",
        "contact_name": "Dr. Allan Lebovitz, DDS",
        "phone": "(718) 859-6006",
        "address": "1490 Ocean Avenue, Suite 1",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11230",
        "borough": "Brooklyn",
        "neighborhood": "Midwood",
        "online_presence": "Healthgrades, EDP Dental, Delta Dental — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Mark S. Cerrachio, DDS",
        "contact_name": "Dr. Mark S. Cerrachio, DDS",
        "phone": "(718) 622-7231",
        "address": "774 Carroll Street",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11215",
        "borough": "Brooklyn",
        "neighborhood": "Park Slope",
        "online_presence": "Healthgrades, WebMD, US News — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Fitzroy L. Maitland, DDS PC",
        "contact_name": "Dr. Fitzroy L. Maitland, DDS",
        "phone": "(718) 282-5128",
        "address": "353 Ocean Avenue, Apt 1H",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11226",
        "borough": "Brooklyn",
        "neighborhood": "Prospect-Lefferts Gardens / Flatbush",
        "online_presence": "DentalPlans, Healthgrades, WebMD — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Vincent A. Settecase, DDS / Leon Tuberman, DMD",
        "contact_name": "Dr. Vincent A. Settecase, DDS; Dr. Leon Tuberman, DMD",
        "phone": "(718) 836-7109",
        "address": "355 Ovington Avenue, Suite 100",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11209",
        "borough": "Brooklyn",
        "neighborhood": "Bay Ridge",
        "online_presence": "Yelp, Healthgrades — no practice site found",
        "notes": "Shared Bay Ridge suite.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Stephen M. Cohen, DDS",
        "contact_name": "Dr. Stephen M. Cohen, DDS",
        "phone": "(718) 622-2557",
        "address": "1 Plaza Street West, Suite 1A",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11217",
        "borough": "Brooklyn",
        "neighborhood": "Prospect Heights",
        "online_presence": "WebMD and dentist-network directories only",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "German Gelb, DDS",
        "contact_name": "Dr. German Gelb, DDS",
        "phone": "(718) 646-6800",
        "address": "3073 Brighton 13th Street",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11235",
        "borough": "Brooklyn",
        "neighborhood": "Brighton Beach",
        "online_presence": "Healthgrades, WebMD, EDP Dental — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Dental Health PC",
        "contact_name": "Dr. Vadim Leybovich, DDS",
        "phone": "(718) 435-4515",
        "address": "1328 47th Street",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11219",
        "borough": "Brooklyn",
        "neighborhood": "Borough Park",
        "online_presence": "Healthgrades, WebMD, NPI — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Fernandez Dental Office Inc.",
        "contact_name": "Dr. Franklin F. Fernandez, DDS; Dr. Ana L. Fernandez, DDS",
        "phone": "(718) 456-0751",
        "address": "1640 Madison Street, Apt 2 / 1st Floor",
        "city": "Ridgewood",
        "state": "NY",
        "zip": "11385",
        "borough": "Queens",
        "neighborhood": "Ridgewood",
        "online_presence": "Yelp, Healthgrades, WebMD — Google business.site page is 404",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Kyaw & Tan Dental PC",
        "contact_name": "Dr. Maung M. Kyaw, DMD; Dr. Yin Yin Tan, DMD",
        "phone": "(718) 461-4678",
        "address": "42-60 Main Street, Suite 2J",
        "city": "Flushing",
        "state": "NY",
        "zip": "11355",
        "borough": "Queens",
        "neighborhood": "Flushing",
        "online_presence": "Insurance directories and Chinese yellow pages only",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "D&L Dental P.C. / Elina Kats, DDS",
        "contact_name": "Dr. Elina Kats, DDS",
        "phone": "(718) 426-2231",
        "address": "92-11 35th Avenue, Apt 1K",
        "city": "Jackson Heights",
        "state": "NY",
        "zip": "11372",
        "borough": "Queens",
        "neighborhood": "Jackson Heights",
        "online_presence": "Yelp, Zocdoc, Healthgrades — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Scott R. Sherrin, DDS",
        "contact_name": "Dr. Scott R. Sherrin, DDS",
        "phone": "(718) 721-5577",
        "address": "31-80 38th Street",
        "city": "Astoria",
        "state": "NY",
        "zip": "11103",
        "borough": "Queens",
        "neighborhood": "Astoria",
        "online_presence": "WebMD and map listings only",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Alan J. Schwartz, DDS",
        "contact_name": "Dr. Alan J. Schwartz, DDS",
        "phone": "(718) 380-1770",
        "address": "7805 141st Street",
        "city": "Kew Gardens Hills",
        "state": "NY",
        "zip": "11367",
        "borough": "Queens",
        "neighborhood": "Kew Gardens Hills",
        "online_presence": "Yelp and chamber listing — no practice site found",
        "notes": "A separate office exists in Oceanside, NY. This row is Queens only.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Prism Dental PC",
        "contact_name": "Dr. Barrington O. Anderson, DDS",
        "phone": "(718) 341-2300",
        "address": "225-15 Linden Boulevard",
        "city": "Cambria Heights",
        "state": "NY",
        "zip": "11411",
        "borough": "Queens",
        "neighborhood": "Cambria Heights",
        "online_presence": "DentalPlans, Delta Dental, Yelp — no practice site found",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Lee Schwartz, DDS",
        "contact_name": "Dr. Lee Schwartz, DDS",
        "phone": "(718) 459-8288",
        "address": "68-64 Yellowstone Boulevard, Suite B1",
        "city": "Forest Hills",
        "state": "NY",
        "zip": "11375",
        "borough": "Queens",
        "neighborhood": "Forest Hills",
        "online_presence": "Yelp and Healthgrades — no Visit Website link",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Parkchester Family Dental Service",
        "contact_name": "Dr. Herrick Lai, DDS (listed at this office)",
        "phone": "(718) 863-0200",
        "address": "64 Metropolitan Oval, Suite 9",
        "city": "Bronx",
        "state": "NY",
        "zip": "10462",
        "borough": "Bronx",
        "neighborhood": "Parkchester",
        "online_presence": "Yelp and insurance directories — no practice site found",
        "notes": "Older directories also list (718) 892-5095.",
        "source": "Manual verify Aug 2026",
    },
    {
        "name": "Hebri S. Ballal, DDS",
        "contact_name": "Dr. Hebri S. Ballal, DDS",
        "phone": "(718) 948-3707",
        "address": "3371 Richmond Avenue",
        "city": "Staten Island",
        "state": "NY",
        "zip": "10312",
        "borough": "Staten Island",
        "neighborhood": "Eltingville / Great Kills area",
        "online_presence": "Yelp, EDP Dental, MapQuest — no practice site found",
        "source": "Manual verify Aug 2026",
    },
]


def seed() -> int:
    init()
    created = 0
    for item in SEED:
        rec = {
            **item,
            "niche": "dentist",
            "has_website": 0,
            "status": "new",
        }
        _id, is_new = upsert_lead(rec)
        if is_new:
            created += 1
    return created


if __name__ == "__main__":
    n = seed()
    print(f"Seeded {n} new dental leads ({len(SEED)} in file)")
