/** JSON Schema fragments used with Grok structured outputs. */

export const parsedResumeJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "name",
    "email",
    "phone",
    "summary",
    "skills",
    "experience",
    "education",
    "projects",
    "certifications",
    "achievements",
    "technologies",
    "jobTitles",
    "yearsOfExperience",
  ],
  properties: {
    name: { type: "string" },
    email: { type: "string" },
    phone: { type: "string" },
    summary: { type: "string" },
    skills: { type: "array", items: { type: "string" } },
    experience: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "company", "dates", "highlights"],
        properties: {
          title: { type: "string" },
          company: { type: "string" },
          dates: { type: "string" },
          highlights: { type: "array", items: { type: "string" } },
        },
      },
    },
    education: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["school", "degree", "year"],
        properties: {
          school: { type: "string" },
          degree: { type: "string" },
          year: { type: "string" },
        },
      },
    },
    projects: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "description", "technologies"],
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          technologies: { type: "array", items: { type: "string" } },
        },
      },
    },
    certifications: { type: "array", items: { type: "string" } },
    achievements: { type: "array", items: { type: "string" } },
    technologies: { type: "array", items: { type: "string" } },
    jobTitles: { type: "array", items: { type: "string" } },
    yearsOfExperience: { type: "number" },
  },
} as const;

export const internalAnalysisJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "careerTrajectory",
    "primarySkills",
    "secondarySkills",
    "industry",
    "resumeStrengths",
    "resumeWeaknesses",
    "skillGaps",
    "questionOpportunities",
    "topicsToCover",
    "openingQuestion",
    "openingTopic",
    "openingType",
  ],
  properties: {
    careerTrajectory: { type: "string" },
    primarySkills: { type: "array", items: { type: "string" } },
    secondarySkills: { type: "array", items: { type: "string" } },
    industry: { type: "string" },
    resumeStrengths: { type: "array", items: { type: "string" } },
    resumeWeaknesses: { type: "array", items: { type: "string" } },
    skillGaps: { type: "array", items: { type: "string" } },
    questionOpportunities: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["claim", "question"],
        properties: {
          claim: { type: "string" },
          question: { type: "string" },
        },
      },
    },
    topicsToCover: { type: "array", items: { type: "string" } },
    openingQuestion: { type: "string" },
    openingTopic: { type: "string" },
    openingType: { type: "string" },
  },
} as const;

export const interviewTurnJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "nextQuestion",
    "questionType",
    "difficulty",
    "shouldFollowUp",
    "followUpFocus",
    "topic",
    "interviewComplete",
    "reason",
    "evaluation",
  ],
  properties: {
    nextQuestion: { type: "string" },
    questionType: { type: "string" },
    difficulty: { type: "string" },
    shouldFollowUp: { type: "boolean" },
    followUpFocus: { type: "string" },
    topic: { type: "string" },
    interviewComplete: { type: "boolean" },
    reason: { type: "string" },
    evaluation: {
      anyOf: [
        { type: "null" },
        {
          type: "object",
          additionalProperties: false,
          required: [
            "technical",
            "relevance",
            "depth",
            "problemSolving",
            "communication",
            "specificity",
            "ownership",
            "confidence",
            "overall",
            "notes",
          ],
          properties: {
            technical: { type: "number" },
            relevance: { type: "number" },
            depth: { type: "number" },
            problemSolving: { type: "number" },
            communication: { type: "number" },
            specificity: { type: "number" },
            ownership: { type: "number" },
            confidence: { type: "number" },
            overall: { type: "number" },
            notes: { type: "string" },
          },
        },
      ],
    },
  },
} as const;

export const finalReportJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "overallScore",
    "scores",
    "readiness",
    "readinessPercent",
    "readinessReason",
    "executiveSummary",
    "strengths",
    "weaknesses",
    "questionAnalysis",
    "communicationAnalysis",
    "technicalAnalysis",
    "resumeConsistency",
    "recommendations",
    "improvementPlan",
    "finalRecommendation",
  ],
  properties: {
    overallScore: { type: "number" },
    scores: {
      type: "object",
      additionalProperties: false,
      required: [
        "technical",
        "communication",
        "problemSolving",
        "confidence",
        "roleKnowledge",
        "behavioral",
        "resumeKnowledge",
      ],
      properties: {
        technical: { type: "number" },
        communication: { type: "number" },
        problemSolving: { type: "number" },
        confidence: { type: "number" },
        roleKnowledge: { type: "number" },
        behavioral: { type: "number" },
        resumeKnowledge: { type: "number" },
      },
    },
    readiness: { type: "string" },
    readinessPercent: { type: "number" },
    readinessReason: { type: "string" },
    executiveSummary: { type: "string" },
    strengths: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "detail", "evidence"],
        properties: {
          title: { type: "string" },
          detail: { type: "string" },
          evidence: { type: "string" },
        },
      },
    },
    weaknesses: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "whatHappened", "whyItMatters", "example", "howToImprove"],
        properties: {
          title: { type: "string" },
          whatHappened: { type: "string" },
          whyItMatters: { type: "string" },
          example: { type: "string" },
          howToImprove: { type: "array", items: { type: "string" } },
        },
      },
    },
    questionAnalysis: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "order",
          "question",
          "candidateAnswer",
          "score",
          "whatWentWell",
          "whatWasMissing",
          "betterApproach",
          "strongAnswerIncludes",
        ],
        properties: {
          order: { type: "number" },
          question: { type: "string" },
          candidateAnswer: { type: "string" },
          score: { type: "number" },
          whatWentWell: { type: "string" },
          whatWasMissing: { type: "string" },
          betterApproach: { type: "string" },
          strongAnswerIncludes: { type: "array", items: { type: "string" } },
        },
      },
    },
    communicationAnalysis: {
      type: "object",
      additionalProperties: false,
      required: [
        "clarity",
        "structure",
        "conciseness",
        "fillerWords",
        "storytelling",
        "starUsage",
        "technicalExplanation",
        "suggestion",
      ],
      properties: {
        clarity: { type: "string" },
        structure: { type: "string" },
        conciseness: { type: "string" },
        fillerWords: { type: "string" },
        storytelling: { type: "string" },
        starUsage: { type: "string" },
        technicalExplanation: { type: "string" },
        suggestion: { type: "string" },
      },
    },
    technicalAnalysis: {
      type: "object",
      additionalProperties: false,
      required: ["summary", "strengths", "gaps", "recommendation"],
      properties: {
        summary: { type: "string" },
        strengths: { type: "array", items: { type: "string" } },
        gaps: { type: "array", items: { type: "string" } },
        recommendation: { type: "string" },
      },
    },
    resumeConsistency: {
      type: "object",
      additionalProperties: false,
      required: [
        "supportedClaims",
        "needsClarification",
        "listedButNotDemonstrated",
        "demonstratedBeyondResume",
        "summary",
      ],
      properties: {
        supportedClaims: { type: "array", items: { type: "string" } },
        needsClarification: { type: "array", items: { type: "string" } },
        listedButNotDemonstrated: { type: "array", items: { type: "string" } },
        demonstratedBeyondResume: { type: "array", items: { type: "string" } },
        summary: { type: "string" },
      },
    },
    recommendations: { type: "array", items: { type: "string" } },
    improvementPlan: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["day", "title", "focus"],
        properties: {
          day: { type: "number" },
          title: { type: "string" },
          focus: { type: "string" },
        },
      },
    },
    finalRecommendation: { type: "string" },
  },
} as const;
